name: Performance Tests

on:
    pull_request:
    release:
        types: [published]
    push:
        branches: [trunk]
    workflow_dispatch:
        inputs:
            branches:
                description: 'branches or commits to compare (comma separated)'
                required: true
            wpversion:
                description: 'The base WP version to use for the tests (latest or 6.0, 6.1...)'
                required: false
                default: 'latest'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    generate-performance-suite-matrix:
        name: Generate performance suite matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.suites.outputs.matrix }}
        steps:
            - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Use desired version of Node.js
              uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
              with:
                  node-version-file: '.nvmrc'
                  check-latest: true
                  cache: npm

            - name: Find and output suites
              id: suites
              run: echo matrix=$(node -e "console.log( JSON.stringify( require('fs').readdirSync('test/performance/specs').map( specFile => require('path').basename( specFile, '.spec.js' ) ) ) )") | tee "$GITHUB_OUTPUT"

            - name: print
              run: echo ${{ steps.suites.outputs.matrix }}

    performance:
        name: Run performance tests ${{ matrix.suite }}
        needs: generate-performance-suite-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                suite: ${{ fromJSON( needs.generate-performance-suite-matrix.outputs.matrix ) }}
        if: ${{ github.repository == 'WordPress/gutenberg' }}
        env:
            WP_ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

        steps:
            - run: echo ${{ matrix.suite }}
